version: '3'

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/mariadb
      o: bind
networks:
  db:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD_HERE
      MYSQL_USER: YOUR_MYSQL_USER_HERE
      MYSQL_PASSWORD: YOUR_USER_PW_HERE
      MYSQL_DATABASE: brick_game
    ports:
      - "40000:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "40001:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - db

  node-app:
    build: ./backend/.
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: YOUR_MYSQL_USER_HERE
      DB_PASSWORD: YOUR_USER_PW_HERE
      DB_NAME: brick_game
    networks:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:3000"
    networks:
      - db

